spring:
  application:
    name: example-jwt-webmvc

  config:
    import:
      - classpath:/app/jwt/jwt.yml

  profiles:
    active: prod

  datasource:
    driver-class-name: org.h2.Driver
    # ${환경변수}, ${환경변수:없을 때 대체값}
    url: ${DB_URL:jdbc:h2:mem:testdb} # application.yml에선 ${DB_URL}, application-local.yml에선 ${DB_URL:기본값}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

    # connection pool (usage: hikari pool)
    hikari:
      connection-timeout: 30_000
      idle-timeout: 60_000
      max-lifetime: 1_800_000
      maximum-pool-size: 300
      minimum-idle: 5
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true # profile 설정 안 해도 확인할 수 있도록 임시로 true 함.
    hibernate:
      ddl-auto: none # flyway 사용하면 none 또는 validate (엄격한 경우 validate)

  flyway:
    baseline-on-migrate: true # flyway schema history 테이블이 없다면 생성한다.
